
services:
  app:
    container_name: chatwit_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/src/node_modules
      - ./localhost-key.pem:/src/localhost-key.pem
      - ./localhost.pem:/src/localhost.pem
    command: npm run dev
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: .
          target: /src
          ignore:
            - node_modules/
            - ".git/"
            - "Dockerfile*"
            - "docker-compose*.yml"
        - action: rebuild
          path: package.json

volumes:
  node_modules:
    driver: local

networks:
  app-network:
    driver: bridge
