version: "3.8"

services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"  # Altere para a versão desejada, ex.: "10", "11e", etc.
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    volumes:
      - windows-storage:/storage  # Volume persistente para manter os programas instalados
    restart: always
    stop_grace_period: 2m

volumes:
  windows-storage:
