#docker-compose -f docker-compose-redis.yml up -d

services:
  redis:
    image: redis:7-alpine
    container_name: chatwit_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - minha_rede
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  minha_rede:
    external: true
    name: minha_rede
