version: "3.9"
#docker-compose -f docker-compose-prod.yml up --build -d
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: chatwit_prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: npm run start
