FROM node:22-slim

WORKDIR /src

COPY package*.json ./
COPY prisma ./prisma

COPY . .
RUN npm install
RUN npm i @napi-rs/simple-git-linux-x64-gnu
RUN npx prisma generate
EXPOSE 3000

RUN apt-get update ; apt-get install -y apparmor-utils

#COPY prisma ./prisma

CMD [ "npm", "run", "dev" ]
