services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    container_name: chatwit_dev
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USE_TLS: ${REDIS_USE_TLS}
      BASEROW_TOKEN: ${BASEROW_TOKEN}
      BASEROW_TABLE_ID: ${BASEROW_TABLE_ID}
      WEBHOOK_URL: ${WEBHOOK_URL}
    command: npm run dev
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    container_name: bull_worker_dev
    volumes:
      - .:/src
      - /src/node_modules
    environment:
      NODE_ENV: development
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USE_TLS: ${REDIS_USE_TLS}
      BASEROW_TOKEN: ${BASEROW_TOKEN}
      BASEROW_TABLE_ID: ${BASEROW_TABLE_ID}
      WEBHOOK_URL: ${WEBHOOK_URL}
    command: npm run worker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
