// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";
import { SessionProvider } from "next-auth/react";
import NavbarGeral from "@/components/navbarGeral";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className={cn(inter.className, "min-h-screen")}>
        {/* Providers GLOBAIS (Session, Theme) */}
        <SessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* Navbar Geral no topo; some nas rotas /dashboard */}
            <NavbarGeral />

            {/* Container principal */}
            <main className="min-h-screen p-4 md:p-8">{children}</main>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
